config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :patients

  root to: "patients#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord

  before_create :calculateASA
  before_update :calculateASA


  def calculateASA
  	#initialise the risk score as 0
  	risk = 0
  	#Q1
  	if self.q1 == "Very good" 
  		risk = risk
  	end

  	if self.q1 == "No abnormalities" 
  		risk = risk -2
  	end

  	if self.q1 == "Not good" 
  		risk = risk +2
  	end

  	if self.q1 == "I am diagnosed with dementia" 
  		risk = risk + 2
  	end

  	if self.q1 == "Very sick" 
  		risk = risk +2
  	end

  	if self.q1 == "Bedbound at all times" 
  		risk = risk +24
  	end
  	#Q2
  	if self.q2 == "I can do everything I want" 
  		risk = risk-2
  	end

  	if self.q2 == "Slightly impaired, but I feel no impairments in daily activities" 
  		risk = risk
  	end

  	if self.q2 == "Impaired, I can only take care of domestic chores" 
  		risk = risk +2
  	end

  	if self.q2 == "I am completely dependent on help from others" 
  		risk = risk +4
  	end
  	#Q3 CCF
  	if self.q3 == "No" 
  		risk = risk
  	end

  	if self.q3 == "Yes, only during heavy labour" 
  		risk = risk+1
  	end

  	if self.q3 == "Yes, during climbing the stairs, in the wind, stress" 
  		risk = risk +2
  	end

  	if self.q3 == "Yes, daily, not at rest" 
  		risk = risk +5
  	end

  	if self.q3 == "Yes, at rest and increased during any activity" 
  		risk = risk +8
  	end
  	#Q4 Angina
  	if self.q4 == "No" 
  		risk = risk
  	end

  	if self.q4 == "Yes, only during heavy labour" 
  		risk = risk+1
  	end

  	if self.q4 == "Yes, during climbing the stairs, in the wind, stress" 
  		risk = risk +2
  	end

  	if self.q4 == "Yes, daily, not at rest" 
  		risk = risk +5
  	end

  	if self.q4 == "Yes, at rest and increased during any activity" 
  		risk = risk +8
  	end
  	#Q5 Infarct
  	if self.q5 == "No" 
  		risk = risk
  	end

  	if self.q5 == "Yes, longer than 12 months ago" 
  		risk = risk+2
  	end

  	if self.q5 == "Yes, longer than 6 months ago" 
  		risk = risk +3
  	end

  	if self.q5 == "Yes, longer than 3 months ago" 
  		risk = risk +4
  	end

  	if self.q5 == "Yes, in the last 3 months" 
  		risk = risk +6
  	end
  	#Q6 Arrest
  	if self.q6 == "No" 
  		risk = risk
  	end

  	if self.q6 == "Yes, longer than 12 months ago" 
  		risk = risk+1
  	end

  	if self.q6 == "Yes, longer than 6 months ago" 
  		risk = risk +3
  	end

  	if self.q6 == "Yes, longer than 3 months ago" 
  		risk = risk +4
  	end

  	if self.q6 == "Yes, in the last 3 months" 
  		risk = risk +6
  	end
  	#Q7 Cathlab
  	if self.q7 == "No" 
  		risk = risk
  	end

  	if self.q7 == "Yes, longer than 6 months ago" 
  		risk = risk+1
  	end

  	if self.q7 == "Yes, longer than 3 months ago" 
  		risk = risk +3
  	end

  	if self.q7 == "Yes, longer than 3 weeks ago" 
  		risk = risk +4
  	end

  	if self.q7 == "Yes, in the last 3 weeks" 
  		risk = risk +6
  	end
  	#Q8 Palps
  	if self.q8 == "No" 
  		risk = risk
  	end

  	if self.q8 == "Yes, and I do not take treatment for it" 
  		risk = risk+1
  	end

  	if self.q8 == "Yes, and I take treatment for it" 
  		risk = risk +2
  	end
    #Q9 Murmur
    if self.q9 == "No" 
      risk = risk
    end

    if self.q9 == "Yes" 
      risk = risk+2
    end

    if self.q9 == "Yes, and I've had a procedure to fix it" 
      risk = risk +2
    end
    #Q10 Htn
    if self.q10 == "No" 
      risk = risk
    end

    if self.q10 == "I don't know" 
      risk = risk
    end

    if self.q10 == "Yes/it's controlled on tablets" 
      risk = risk +2
    end
    #Q11 Cholesterol
    if self.q11 == "No" 
      risk = risk
    end

    if self.q11 == "Yes/it's controlled on tablets" 
      risk = risk+2
    end
    #Q12 Diabetes
    if self.q12 == "No" 
      risk = risk
    end

    if self.q12 == "Yes, treatment with diet" 
      risk = risk+1
    end

    if self.q12 == "Yes, treatment with oral medication" 
      risk = risk +3
    end

    if self.q12 == "Yes, treatment with insulin" 
      risk = risk +4
    end
    #Q13 Stroke
    if self.q13 == "No" 
      risk = risk
    end

    if self.q13 == "Yes, but I've completely recovered" 
      risk = risk
    end

    if self.q13 == "Yes, and I have not fully recovered" 
      risk = risk +2
    end

    if self.q13 == "Yes, in the last two months" 
      risk = risk +4
    end
    #Q14 Asthma
    if self.q14 == "No" 
      risk = risk
    end

    if self.q14 == "Yes, but I rarely need my inhailer" 
      risk = risk
    end

    if self.q14 == "Yes, I need my inhaler about once a week" 
      risk = risk +1
    end

    if self.q14 == "Yes, I need my inhaler every day" 
      risk = risk +3
    end

    if self.q14 == "Yes, I need my inhaler every day and it's been getting worse over the past 6 months" 
      risk = risk +4
    end
    #Q15 COPD
    if self.q15 == "No" 
      risk = risk
    end

    if self.q15 == "Yes, it affects me during heavy exercise" 
      risk = risk+1
    end

    if self.q15 == "Yes, it affects me when climbing the stairs, in the wind, during stress" 
      risk = risk +4
    end

    if self.q15 == "Yes, I'm breathless at rest or I need oxygen therapy at home" 
      risk = risk+8
    end
    #Q16 OSA
    if self.q16 == "No" 
      risk = risk
    end

    if self.q16 == "Yes" 
      risk = risk+4
    end
    #Q17 Kidney
    if self.q17 == "No" 
      risk = risk
    end

    if self.q17 == "Yes, I had a problem before but it has completely resolved (acute injury)" 
      risk = risk
    end

    if self.q17 == "Yes, my doctor has told me I must limit how much fluid I drink each day" 
      risk = risk+3
    end

    if self.q17 == "Yes, I am getting dialysis" 
      risk = risk+6
    end

    if self.q17 == "Yes, I have had a kidney transplant or kidney opperation" 
      risk = risk+2
    end
    #Q18 Liver
    if self.q18 == "No" 
      risk = risk
    end

    if self.q18 == "Yes, but with complete recovery" 
      risk = risk
    end

    if self.q18 == "Yes, liver cirrhosis has been diagnosed" 
      risk = risk+4
    end

    if self.q18 == "Yes, I've had a procedure done on my liver" 
      risk = risk+1
    end
    #Q19 Weight Loss
    if self.q19 == "No" 
      risk = risk
    end

    if self.q19 == "Yes" 
      risk = risk+1
    end

    if self.q19 == "Yes, more than 25% of previous bodyweight" 
      risk = risk+2
    end
    #Q20 Smoker
    if self.q20 == "No" 
      risk = risk
    end
    
    if self.q20 == "I've quit in the last five years" 
      risk = risk+3
    end

    if self.q20 == "Yes" 
      risk = risk+4
    end
    #Q21 Alcohol
    if self.q21 == "No" 
      risk = risk
    end

    if self.q21 == "Yes, but less than 2 bottles of wine or 8 pints a week" 
      risk = risk
    end

    if self.q21 == "Yes, but more than 2 bottles of wine or 8 pints a week" 
      risk = risk
    end

    if self.q19 == "Yes, more than a bottle of wine or 4 pints most days" 
      risk = risk+4
    end
    #Q22 Drugs
    if self.q22 == "No" 
      risk = risk
    end

    if self.q22 == "No, not anymore" 
      risk = risk
    end

    if self.q22 == "Yes, every once in a while" 
      risk = risk
    end

    if self.q22 == "Yes, more the once a week" 
      risk = risk+2
    end


    #Q22 Drugs - convert score to cASA grade
    if risk <= 3
      self.asa = 1
    end

  	if risk >= 3
  		self.asa = 2
  	end

  	if risk >= 10
  		self.asa = 3
  	end

    if risk >= 20
      self.asa = 4
    end

  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # def index
  #  @patients = Patient.where(["firstName LIKE ? AND surName LIKE ? AND dob LIKE ? AND hospital LIKE ? AND opDate LIKE ?","%#{params[:searchFirst]}%","%#{params[:searchSur]}%","%#{params[:dob]}%","%#{params[:searchHos]}%","%#{params[:searchOpDate]}%"])
  # end

  # GET /patients/1
  # GET /patients/1.json
  def show
    
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:firstName, :surName, :dob, :gender, :hospital, :opDate, :q1, :q2, :q3, :q4, :q5, :q6, :q7, :q8, :q9, :q10, :q11, :q12, :q13, :q14, :q15, :q16, :q17, :q18, :q19, :q20, :q21, :q22, :asa)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :"First Name" %><br>
    <%= form.text_field :firstName, class: "form-control", id: :patient_firstName %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Surname" %><br>
    <%= form.text_field :surName, class: "form-control", id: :patient_surName %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Date of Birth" %>&nbsp &nbsp 
    <%= form.date_select :dob, :start_year=>1900,:end_year=>2030, id: :patient_dob %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Gender" %>&nbsp &nbsp 
    <%= form.select :gender, ["","male", "female"], id: :patient_gender %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Which hospital are you having the opperation in?" %>&nbsp &nbsp 
    <%= form.select :hospital, ["","Limerick Regional", "St. Johns"], id: :patient_hospital %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"What date are you having the opperation on? (If you don't know your opperation date, please select todays date." %>&nbsp &nbsp 
    <%= form.date_select :opDate, :start_year=>2017,:end_year=>2027, id: :patient_opDate %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"How would you rate your overall health" %><br>
    <%= form.select :q1, ["","Very good", "No abnormalities", "Not good", "I am diagnosed with dementia", "Very sick", "Bedbound at all times"], id: :patient_q1 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"How is your physical condition in general?" %><br>
    <%= form.select :q2, ["","I can do everything I want", "Slightly impaired, but I feel no impairments in daily activities", "Impaired, I can only take care of domestic chores", "I am completely dependent on help from others"],  id: :patient_q2 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you have a heart condition that impedes your physical efforts (as a result of tiredness, pain or shortness of breath)?" %><br>
    <%= form.select :q3, ["","No", "Yes, only during heavy labour", "Yes, during climbing the stairs, in the wind, stress", "Yes, daily, not at rest", "Yes, at rest and increased during any activity"], id: :patient_q3 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Have you ever experienced any feeling of pain or tightness in the chest?" %><br>
    <%= form.select :q4, ["","No", "Yes, only during heavy labour", "Yes, during climbing the stairs, in the wind, stress", "Yes, daily, not at rest", "Yes, at rest and increased during any activity"], id: :patient_q4 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Have you ever had a heart attack or a mini heart attack?" %><br>
    <%= form.select :q5, ["","No", "Yes, longer than 12 months ago", "Yes, longer than 6 months ago", "Yes, longer than 3 months ago", "Yes, in the last 3 months"], id: :patient_q5 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Have you ever had a cardiac arrest? This is where your heart stops beating and you needed CPR" %><br>
    <%= form.select :q6, ["","No", "Yes, longer than 12 months ago", "Yes, longer than 6 months ago", "Yes, longer than 3 months ago", "Yes, in the last 3 months"], id: :patient_q6 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Have you ever undergone any cardiac surgery or had an angiogram test done?" %><br>
    <%= form.select :q7, ["","No", "Yes, longer than 6 months ago", "Yes, longer than 3 months ago", "Yes, longer than 3 weeks ago", "Yes, in the last 3 weeks"], id: :patient_q7 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you ever get palpitations or a concerning fluttering sensation in your chest?" %><br>
    <%= form.select :q8, ["","No", "Yes, and I do not take treatment for it", "Yes, and I take treatment for it"], id: :patient_q8 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Have you been told you have a heart murmur? (an abnormal sound heard with a stethoscope?" %><br>
    <%= form.select :q9, ["","No", "Yes", "Yes, and I've had a procedure to fix it"], id: :patient_q9 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you have high blood pressure?" %><br>
    <%= form.select :q10, ["","No", "I don't know", "Yes/it's controlled on tablets",], id: :patient_q10 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you have high cholesterol?" %><br>
    <%= form.select :q11, ["","No", "Yes/it's controlled on tablets"], id: :patient_q11 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you receive treatment for diabetes (high blood sugar level)?" %><br>
    <%= form.select :q12, ["","No", "Yes, treatment with diet", "Yes, treatment with oral medication", "Yes, treatment with insulin"], id: :patient_q12 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Have you ever had a stroke?" %><br>
    <%= form.select :q13, ["","No", "Yes, but I've completely recovered", "Yes, and I have not fully recovered", "Yes, in the last two months"], id: :patient_q13 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you receive treatment for asthma?" %><br>
    <%= form.select :q14, ["","No", "Yes, but I rarely need my inhailer", "Yes, I need my inhaler about once a week", "Yes, I need my inhaler every day", "Yes, I need my inhaler every day and it's been getting worse over the past 6 months"], id: :patient_q14 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you have difficulty with your breathing from smoking cigarettes, or do you have a diagnosis of COPD/bronchitis/emphysaema" %><br>
    <%= form.select :q15, ["","No", "Yes, it affects me during heavy exercise", "Yes, it affects me when climbing the stairs, in the wind, during stress", "Yes, I'm breathless at rest or I need oxygen therapy at home"], id: :patient_q15 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you have a diagnosis of Sleep Apnoea?" %><br>
    <%= form.select :q16, ["","No", "Yes"], id: :patient_q16 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you have any renal problems or kidney impairment?" %><br>
    <%= form.select :q17, ["","No", "Yes, I had a problem before but it has completely resolved (acute injury)", "Yes, my doctor has told me I must limit how much fluid I drink each day", "Yes, I am getting dialysis", "Yes, I have had a kidney transplant"], id: :patient_q17 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Have you ever had jaundice or any liver problems?" %><br>
    <%= form.select :q18, ["","No", "Yes, but with complete recovery", "Yes, liver cirrhosis has been diagnosed", "Yes, I've had a procedure done on my liver"], id: :patient_q18 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Have you ever unintentionally lost more than 10 kg in a short period of time? If you were trying to lose weight through diet and exercise, please pick no." %><br>
    <%= form.select :q19, ["","No", "Yes", "Yes, more than 25% of previous bodyweight"], id: :patient_q19 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you smoke?" %><br>
    <%= form.select :q20, ["","No", "I've quit in the last five years", "Yes"], id: :patient_q20 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you consume alcohol?" %><br>
    <%= form.select :q21, ["","No", "Yes, one drink per day", "Yes, 2-3 drinks per day", "Yes, more than 3 drinks per day"], id: :patient_q21 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.label :"Do you ever take illicit drugs (Cocaine, Heroin, Ecstasy)?" %><br>
    <%= form.select :q22, ["","No", "No, not anymore", "Yes, every once in a while", "Yes, more the once a week"], id: :patient_q22 %>
  </div>
  <hr>

  <div class="form-group">
    <%= form.submit "Submit for Assessment", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<% if user_signed_in? %>
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>
<% else %>
This page is not available to users who are not signed in. 
<% end %>

app/views/patients/index.html.erb
<% if user_signed_in? %>
<div class = "panel panel-default">
  <div class ="panel-heading">
  <h1>Patient Assessments</h1>
</div>
<div class ="panel-body">

<br><hr>
<%= form_tag patients_path, :method => 'get' do %>
<%= text_field_tag :searchFirst, params[:searchFirst], placeholder: 'First Name' %>&emsp;&emsp;&emsp;&emsp;
<%= text_field_tag :searchSur, params[:searchSur], placeholder: 'Surname' %>&emsp;&emsp;&emsp;&emsp;
<%= text_field_tag :dob, params[:dob], placeholder: 'Date Of Brith' %>&emsp;&emsp;&emsp;&emsp;
<%= text_field_tag :searchHos, params[:searchHos], placeholder: 'Hospital' %>&emsp;&emsp;&emsp;&emsp;
<%= text_field_tag :SearchOpDate, params[:SearchOpDate], placeholder: 'Date of Surgery' %>&emsp;&emsp;&emsp;&emsp;

<%= submit_tag "Search", class: "btn-sm btn-group btn-primary "%>
<% end %>

<hr>
<p><i>Tip: Use the search bar above to filter patient records, or click on a table header to sort the patient records</i></p>
<div class="table-responsive">
<table class="table sortable">
  <thead>
    <tr>
      <th role="button">First Name</th>
      <th role="button">Surname</th>
      <th role="button">Date of Birth</th>
      <th role="button">Hospital</th>
      <th role="button">Date</th>
      <th role="button">ASA</th>
      <th colspan="3" role="button"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.firstName %></td>
        <td><%= patient.surName %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.hospital %></td>
        <td><%= patient.opDate %></td>
        <td><strong><%= patient.asa %></strong></td>
        <td>
        <%= link_to 'Details', patient, class: "btn-sm btn-group btn-primary " %>
        <%= link_to 'Edit', edit_patient_path(patient), class: "btn-sm btn-group btn-success " %>
        <%= link_to 'Delete', patient, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-sm btn-group btn-danger " %>
      </td>
        
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Patient', new_patient_path, class: "btn  btn-primary " %>
</div>
</div>


<% else %>
  <div class="col-lg-6">
  <div class="jumbotron">
    <h1>Patients</h2>
    <hr>
    <p>APAT, or Anaesthetic Preoperative Assessment is a quick and easy online assessment tool that allows us to get to know a little bit about our patients before they come in for surgery in Irish hospitals.
    If you have been asked to complete an assessment by a surgeon, simply click the button below and answer our questions.</p>
    <p>
      <%= button_to "Start Your Assessment »", new_patient_path, class: "btn btn-primary btn-lg", method: :get %>
    </p>
  </div>
</div>
    <div class="col-lg-6">

  <div class="jumbotron">
    <h1>Doctors</h2>
    <hr>
    <p>Anaesthetists and Surgeons who have registered to use APAT can sign in to view assessments.</p>
     <%= button_to "Doctors Sign In »", new_user_session_path, class: "btn btn-info btn-lg", method: :get %>
    </p>
  </div>
</div>
<%end%>

app/views/patients/new.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h3>Please answer the following questions to complete your assessment</h3>
	</div>
	<div class="panel-body">

<%= render 'form', patient: @patient %>

</div>
</div>

app/views/patients/show.html.erb
<% if user_signed_in? %>
<div id="page-wrapper">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Patient: <%= @patient.firstName %> <%= @patient.surName %></h2>
      </div>
      <div class="panel-body">
        <div class="col-lg-6">

<p>
  <strong>Firstname:</strong>
  <%= @patient.firstName %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @patient.surName %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @patient.dob %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @patient.gender %>
</p>

<p>
  <strong>Hospital:</strong>
  <%= @patient.hospital %>
</p>

<p>
  <strong>Opperation Date:</strong>
  <%= @patient.opDate %>
</p>

<p>
  <strong>How would you rate your overall health:</strong>
  <%= @patient.q1 %>
</p>

<p>
  <strong>How is your physical condition in general?:</strong>
  <%= @patient.q2 %>
</p>

<p>
  <strong>Do you have a heart condition that impedes your physical efforts (as a result of tiredness, pain or shortness of breath)?:</strong>
  <%= @patient.q3 %>
</p>

<p>
  <strong>Have you ever experienced any feeling of pain or tightness in the chest?:</strong>
  <%= @patient.q4 %>
</p>

<p>
  <strong>Have you ever had a heart attack?:</strong>
  <%= @patient.q5 %>
</p>

<p>
  <strong>Have you ever had a cardiac arrest?:</strong>
  <%= @patient.q6 %>
</p>

<p>
  <strong>Have you ever undergone any cardiac surgery or heart catheterization?:</strong>
  <%= @patient.q7 %>
</p>

<p>
  <strong>Do you ever get palpitations?:</strong>
  <%= @patient.q8 %>
</p>

<p>
  <strong>Have you been told you have a heart murmur?:</strong>
  <%= @patient.q9 %>
</p>

<p>
  <strong>Do you have high blood pressure?:</strong>
  <%= @patient.q10 %>
</p>

<p>
  <strong>Do you have high cholesterol?:</strong>
  <%= @patient.q11 %>
</p>

<p>
  <strong>Do you receive treatment for diabetes (high blood sugar level)?:</strong>
  <%= @patient.q12 %>
</p>

<p>
  <strong>Have you ever had a stroke?:</strong>
  <%= @patient.q13 %>
</p>

<p>
  <strong>Do you receive treatment for asthma?:</strong>
  <%= @patient.q14 %>
</p>

<p>
  <strong>Do you receive treatment for pulmonary emphysema, chronic obstructive pulmonary disease (COPD) or chronic bronchitis?:</strong>
  <%= @patient.q15 %>
</p>

<p>
  <strong>Do you have Sleep Apnoea?:</strong>
  <%= @patient.q16 %>
</p>

<p>
  <strong>Do you have any renal problems or kidney impairment?:</strong>
  <%= @patient.q17 %>
</p>

<p>
  <strong>Have you ever had jaundice or any liver problems?:</strong>
  <%= @patient.q18 %>
</p>

<p>
  <strong>Have you ever unintentionally lost more than 10 kg in a short period of time?:</strong>
  <%= @patient.q19 %>
</p>

<p>
  <strong>Do you smoke?:</strong>
  <%= @patient.q20 %>
</p>

<p>
  <strong>Do you consume alcohol?:</strong>
  <%= @patient.q21 %>
</p>

<p>
  <strong>Do you ever take illicit drugs (Cocaine, Heroin, Ecstasy)?:</strong>
  <%= @patient.q22 %>
</p>
</div>
<div class="col-lg-3">
<div class="panel panel-default">
      <div class="panel-heading">
        <h3>
        <strong>ASA Grade:</strong>
        <%= @patient.asa %>
        </h3>
      </div>
      <div class="panel-heading">
        &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Edit', edit_patient_path(@patient), class: "btn  btn-primary " %> &nbsp;&nbsp;&nbsp;&nbsp;
        <%= link_to 'Back', patients_path, class: "btn  btn-primary" %>
      </div>



</div>

<% else %>
<br><br><br>
<div class="well">
  <h2>Thank you for completing your assessment! </h2>
  <br><br>
  <p>The results will be made availble for you anaesthesist and surgeon to view prior to your opperation.</p>
  <br><br>
<div>
<% end %>